[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'foundry-tests'
script = 'foundry-scripts'
fs_permissions = [
    { access = "read", path = "./deployment"},
    { access = "read-write", path = "./out" }
]

## set only when the `hardhat` profile is selected
[profile.hardhat]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]

[fuzz]
runs = 10000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[rpc_endpoints]
bsc-test = "https://data-seed-prebsc-1-s1.binance.org:8545/"
bsc = "https://bsc-dataseed1.binance.org/"
local = "http://localhost:8545"
test = "${RPC_TEST}"
