[profile.default]
#src = 'src'
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'foundry-tests'
script = 'foundry-scripts'


## set only when the `hardhat` profile is selected
[profile.hardhat]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
bsc = "https://bsc-dataseed.nariox.org/"
local = "http://localhost:8545"
