name: Unit Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Prepare environment
        run: |
          cp .env.example .env
          npm install
          npm install pm2 -g

      - name: Install project dependencies
        run: |
          forge install --no-git foundry-rs/forge-std@v1.5.6
          forge install --no-git openZeppelin/openzeppelin-contracts@v4.8.3
          forge install --no-git openZeppelin/openzeppelin-contracts-upgradeable@v4.8.3
      - name: Build project
        run: |
          npm run lint:check
          forge build
          npx hardhat compile
      - name: Start Local Chain
        run: |
          pm2 start --name local-chain "anvil -b 1 --block-base-fee-per-gas 0 --chain-id 31337"
          sleep 5
          BYTECODE=$(cast code 0xdb7d0bd38D223048B1cFf39700E4C5238e346f7F --rpc-url https://bsc-dataseed.bnbchain.org)
          cast rpc anvil_setCode 0xdb7d0bd38D223048B1cFf39700E4C5238e346f7F "$BYTECODE" --rpc-url http://127.0.0.1:8545
        env:
          PORT: 8545
      - name: Deploy on Local
        run: |
          npx hardhat run scripts/1-deploy.ts --network local
          sleep 5
      - name: Unit Test
        run: |
          npm run test
