name: Unit Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' # Over here!
        run: |
          npm run install
          curl -L https://foundry.paradigm.xyz | bash
          source /root/.bashrc
          foundryup
          forge install --no-git --no-commit foundry-rs/forge-std@v1.5.6
          forge install --no-git --no-commit openZeppelin/openzeppelin-contracts@v4.8.3
          forge install --no-git --no-commit openZeppelin/openzeppelin-contracts-upgradeable@v4.8.3
      - name: Build project
        run: |
          npm run lint:check
          npm run build
      - name: Start Local Chain
        run: nohup anvil -b 1 &
      - name: Deploy on Local Chain
        run: npm run deploy:local
      - name: Unit Test
        run: npm run test

